/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHederaScheduleService,
  IHederaScheduleServiceInterface,
} from "../../TimedRefundVault.sol/IHederaScheduleService";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "gasLimit",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "uint64",
        name: "expirySecond",
        type: "uint64",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "scheduleCall",
    outputs: [
      {
        internalType: "int64",
        name: "responseCode",
        type: "int64",
      },
      {
        internalType: "address",
        name: "scheduleAddress",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHederaScheduleService__factory {
  static readonly abi = _abi;
  static createInterface(): IHederaScheduleServiceInterface {
    return new Interface(_abi) as IHederaScheduleServiceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHederaScheduleService {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IHederaScheduleService;
  }
}
