/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IHederaScheduleServiceInterface extends Interface {
  getFunction(nameOrSignature: "scheduleCall"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "scheduleCall",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "scheduleCall",
    data: BytesLike
  ): Result;
}

export interface IHederaScheduleService extends BaseContract {
  connect(runner?: ContractRunner | null): IHederaScheduleService;
  waitForDeployment(): Promise<this>;

  interface: IHederaScheduleServiceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  scheduleCall: TypedContractMethod<
    [
      to: AddressLike,
      gasLimit: BigNumberish,
      value: BigNumberish,
      expirySecond: BigNumberish,
      data: BytesLike
    ],
    [[bigint, string] & { responseCode: bigint; scheduleAddress: string }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "scheduleCall"
  ): TypedContractMethod<
    [
      to: AddressLike,
      gasLimit: BigNumberish,
      value: BigNumberish,
      expirySecond: BigNumberish,
      data: BytesLike
    ],
    [[bigint, string] & { responseCode: bigint; scheduleAddress: string }],
    "nonpayable"
  >;

  filters: {};
}
